server:
  port: 8081


spring:
  application:
    name: OrderApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/order_detail
    username: postgres
    password: aanand

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: True